set_level:
  fields:
    weight:
      required: true
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: "kg"
          mode: box
    entry_id:
      required: true
      selector:
        config_entry:
          integration: pellet_tracker
    calibrate:
      required: true
      default: false
      selector:
        boolean:
